### PR TITLE
Fix low real time factor

### PR DESCRIPTION
**Pull request by jrgnicho**
This PR specifies the ODE simulation parameters so that the RTF (real time factor) stays at 1.0.
This change was tested with a total of 40 objects spawned withing 0.5 seconds of each other and with the robot moving to randomized joint poses at all times.  
The RTF stayed at 1.0 when collisions between objects rarely occurred (conveyor belt moving fast power=50.0).  
However, the RTF declined to an average of 0.94 when the conveyor speed was reduced (power=30.0) thus allowing for object collisions to happen very frequently.  My guess is that the simulation had to process more contacts (ODE represents collisions with contacts afaik) that resulted from the collisions.

When the physics parameters are not specified then the simulation will try to run as fast as possible, more on these parameters can be found [here](http://gazebosim.org/tutorials?tut=modifying_world)

This PR contains the changes from PR #43 so that one should be merged first.
@lianjunli  or @alex07zzz  please review.

### CODE REVIEW

**Comment by dhood** [comment]
heads up that for ARIAC we found changing the physics params could impact the ur10's controller performance: https://bitbucket.org/osrf/ariac/issues/15/ur10-not-performing-well-with-current

**Comment by jrgnicho** [comment]
@dhood yes I tested multiple combinations of parameters
max step size: 0.05 - real time update rate: 20,
max step size: 0.02 - real time update rate: 50,
max step size: 0.01 - real time update rate: 100,
max step size: 0.00625 - real time update rate: 160,
max step size: 0.005 - real time update rate: 200,

And did notice the shaking on the first two and motion executions failed on the first three.  I settled on max step size: 0.00625 - real time update rate: 160, after running the simulation with the robot moving and objects spawning for about two hours straight without any noticeable issues.

**Comment by dhood** [comment]
ok great, good to know that there's a combination of values that can work well!

**Comment by jrgnicho** [comment]
@alex07zzz  or @lianjunli  did you get a chance to test this?

**Comment by alex07zzz** [comment]
The real time factor looks pretty good. It is very stable around 1.  But I have some weird error while moving the robot to pick up the object. I am not sure if this comes from my new code. I will take a further look.

**Comment by jrgnicho** [comment]
@alex07zzz then let's work on merging #41 first and evaluate this PR after that

**Comment by alex07zzz** [comment]
@jrgnicho Sure. Thank you for the merging. I think the error is probably coming from my code.

**Comment by jrgnicho** [comment]
@alex07zzz I'll merge this after #41 has been merged, thanks.

**Pull request merged**
