### PR TITLE
Add Gazebo Setup

### PR DESCRIPTION
**Pull request by alex07zzz**
Add Gazebo models, worlds, plugins and ros launch files for gilbreth.

### CODE REVIEW

**Comment by jrgnicho** [comment]
@alex07zzz  thanks for submitting this, could you type up a brief summary of the changes in this PR?

**Comment by alex07zzz** [comment]
Thank you Jorge. I just wrote a readme file about the changes and installations.

**Comment by jrgnicho** [comment]
There are approximately 172 files that have been added, are all of these necessary?

**Comment by alex07zzz** [comment]
Not really. Few of the models and plugins are not necessary. I am working on simplifying these models and plugins. This pull request is just an unfinished environment setup, just in case that someone may want to test the setup. Maybe we can wait for my later submission?

**Comment by jrgnicho** [comment]
OK, we can keep the PR open until you finish cleaning up the clutter from it.   I'll review then, thanks

**Comment by jrgnicho** [comment]
On the other hand, I think it's important to have something that others can run and test.  I'll merge this as it is for now.   Eventually lets create another PR to remove the unnecessary model and code files.  Thanks

**Pull request merged**
